/*
 * outlineRendered.java
 *
 * Created on September 7, 2007, 8:39 PM
 */

package outline;

/**
 *
 * @author  projects
 */
public class outlineRendered extends javax.swing.JInternalFrame {
    
    /** Creates new form outlineRendered */
    public outlineRendered() {
        super("Outlines rendered", 
              true, //resizable
              true, //closable
              true, //maximizable
              true);//iconifiable
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        renderedScrollPane = new javax.swing.JScrollPane();
        renderedOutlines = new javax.swing.JLabel();

        setTitle("Outlines Rendered");
        renderedScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        renderedOutlines.setBackground(new java.awt.Color(255, 255, 255));
        renderedScrollPane.setViewportView(renderedOutlines);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(renderedScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(renderedScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new outlineRendered().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel renderedOutlines;
    private javax.swing.JScrollPane renderedScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
