/*
 * outlineLogger.java
 *
 * Created on September 6, 2007, 3:08 PM
 */

package outline;

/**
 *
 * @author  projects
 */
public class outlineLogger extends javax.swing.JInternalFrame {
    
    /** Creates new form outlineLogger */
    public outlineLogger(String initText) {
        super("Outline logger", 
              true, //resizable
              true, //closable
              true, //maximizable
              true);//iconifiable
        initComponents();
        loggerTextArea.append(initText);
        setClosable(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        loggerScrollPane = new javax.swing.JScrollPane();
        loggerTextArea = new javax.swing.JTextArea();
        loggerLabel = new javax.swing.JLabel();

        setTitle("Log");
        loggerTextArea.setColumns(20);
        loggerTextArea.setLineWrap(true);
        loggerTextArea.setRows(5);
        loggerScrollPane.setViewportView(loggerTextArea);

        loggerLabel.setText("Log of activities");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loggerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loggerLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loggerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loggerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-386)/2, (screenSize.height-155)/2, 386, 155);
    }// </editor-fold>//GEN-END:initComponents
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loggerLabel;
    private javax.swing.JScrollPane loggerScrollPane;
    public javax.swing.JTextArea loggerTextArea;
    // End of variables declaration//GEN-END:variables
    
}
